Python/Flask_Book_Library/project/books/__init__.py
# init file

Python/Flask_Book_Library/project/books/views.py
from flask import render_template, Blueprint, request, redirect, url_for, jsonify
from project import db
from project.books.models import Book
from project.books.forms import CreateBook


# Blueprint for books
books = Blueprint('books', __name__, template_folder='templates', url_prefix='/books')


# Route to display books in HTML
@books.route('/', methods=['GET'])
def list_books():
    # Fetch all books from the database
    books = Book.query.all()
    print('Books page accessed')
    return render_template('books.html', books=books)


# Route to fetch books in JSON format
@books.route('/json', methods=['GET'])
def list_books_json():
    # Fetch all books from the database and convert to JSON
    books = Book.query.all()
    # Create a list of dictionaries representing each book with the required fields
    book_list = [{'name': book.name, 'author': book.author, 'year_published': book.year_published, 'book_type': book.book_type} for book in books]
    return jsonify(books=book_list)


# Route to create a new book
@books.route('/create', methods=['POST', 'GET'])
def create_book():
    data = request.get_json()

    new_book = Book(name=data['name'], author=data['author'], year_published=data['year_published'], book_type=data['book_type'])

    try:
        # Add the new book to the session and commit to save to the database
        db.session.add(new_book)
        db.session.commit()
        print('Book added successfully')
        return redirect(url_for('books.list_books'))
    except Exception as e:
        # Handle any exceptions, such as database errors
        db.session.rollback()
        print('Error creating book')
        return jsonify({'error': f'Error creating book: {str(e)}'}), 500


# Route to update an existing book
@books.route('/<int:book_id>/edit', methods=['POST'])
def edit_book(book_id):
    # Get the book with the given ID
    book = Book.query.get(book_id)
    
    # Check if the book exists
    if not book:
        print('Book not found')
        return jsonify({'error': 'Book not found'}), 404

    try:
        # Get data from the request as JSON
        data = request.get_json()
        
        # Update book details
        book.name = data.get('name', book.name)  # Update if data exists, otherwise keep the same
        book.author = data.get('author', book.author)
        book.year_published = data.get('year_published', book.year_published)
        book.book_type = data.get('book_type', book.book_type)
        
        # Commit the changes to the database
        db.session.commit()
        print('Book edited successfully')
        return jsonify({'message': 'Book updated successfully'})
    except Exception as e:
        # Handle any exceptions
        db.session.rollback()
        print('Error updating book')
        return jsonify({'error': f'Error updating book: {str(e)}'}), 500


# Route to fetch existing book data for editing
@books.route('/<int:book_id>/edit-data', methods=['GET'])
def get_book_for_edit(book_id):
    # Get the book with the given ID
    book = Book.query.get(book_id)
    
    # Check if the book exists
    if not book:
        print('Book not found')
        return jsonify({'success': False, 'error': 'Book not found'}), 404

    # Create a dictionary representing the book data
    book_data = {
        'name': book.name,
        'author': book.author,
        'year_published': book.year_published,
        'book_type': book.book_type
    }
    
    return jsonify({'success': True, 'book': book_data})


# Route to delete a book
@books.route('/<int:book_id>/delete', methods=['POST'])
def delete_book(book_id):
    book = Book.query.get(book_id)
    if not book:
        print('Book not found')
        return jsonify({'error': 'Book not found'}), 404

    try:
        # Delete the book from the database
        db.session.delete(book)
        db.session.commit()
        print('Book deleted successfully')
        return redirect(url_for('books.list_books'))
    except Exception as e:
        # Handle any exceptions, such as database errors
        db.session.rollback()
        print('Error deleting book')
        return jsonify({'error': f'Error deleting book: {str(e)}'}), 500


# Route to get book details based on book name
@books.route('/details/<string:book_name>', methods=['GET'])
def get_book_details(book_name):
        # Find the book by its name
        book = Book.query.filter_by(name=book_name).first()

        if book:
            book_data = {
                'name': book.name,
                'author': book.author,
                'year_published': book.year_published,
                'book_type': book.book_type
            }
            return jsonify(book=book_data)
        else:
            print('Book not found')
            return jsonify({'error': 'Book not found'}), 404

Python/Flask_Book_Library/project/core/views.py
from flask import render_template, Blueprint


# Blueprint for core
core = Blueprint('core', __name__, template_folder='templates', static_folder='static')


# Route to homepage
@core.route('/')
def index():
    print('Homepage accessed')
    return render_template('index.html')

Python/Flask_Book_Library/project/customers/__init__.py
# init file

Python/Flask_Book_Library/project/customers/views.py
from flask import render_template, Blueprint, request, redirect, url_for, jsonify
from project import db
from project.customers.models import Customer


# Blueprint for customers
customers = Blueprint('customers', __name__, template_folder='templates', url_prefix='/customers')


# Route to display customers in HTML
@customers.route('/', methods=['GET'])
def list_customers():
    # Fetch all customers from the database
    customers = Customer.query.all()
    print('Customers page accessed')
    return render_template('customers.html', customers=customers)


# Route to fetch customers in JSON format
@customers.route('/json', methods=['GET'])
def list_customers_json():
    # Fetch all customers from the database and convert to JSON
    customers = Customer.query.all()
    customer_list = [{'name': customer.name, 'city': customer.city, 'age': customer.age} for customer in customers]
    return jsonify(customers=customer_list)


# Route to create a new customer
@customers.route('/create', methods=['POST', 'GET'])
def create_customer():
    data = request.form
    # Check if all required fields are in the form data
    required_fields = ['name', 'city', 'age', 'pesel', 'street', 'appNo']
    if not all(field in data for field in required_fields):
        print('Invalid form data')
        return jsonify({'error': 'Invalid form data'}), 400

    # Create a new customer with all fields
    new_customer = Customer(
        name=data['name'],
        city=data['city'],
        age=data['age'],
        pesel=data['pesel'],
        street=data['street'],
        appNo=data['appNo']
    )

    try:
        db.session.add(new_customer)
        db.session.commit()
        print('Customer added successfully')
        return redirect(url_for('customers.list_customers'))
    except Exception as e:
        db.session.rollback()
        print(f'Error creating customer: {str(e)}')
        return jsonify({'error': f'Error creating customer: {str(e)}'}), 500


# Route to fetch customer data for editing
@customers.route('/<int:customer_id>/edit-data', methods=['GET'])
def edit_customer_data(customer_id):
    # Get the customer with the given ID
    customer = Customer.query.get(customer_id)

    if customer:
        # Convert customer data to a dictionary
        customer_data = {
            'name': customer.name,
            'city': customer.city,
            'age': customer.age
        }
        return jsonify({'success': True, 'customer': customer_data}), 200
    else:
        print('Customer not found')
        return jsonify({'error': 'Customer not found'}), 404


# Route to update an existing customer
@customers.route('/<int:customer_id>/edit', methods=['POST'])
def edit_customer(customer_id):
    # Get the customer with the given ID
    customer = Customer.query.get(customer_id)

    # Check if the customer exists
    if not customer:
        print('Customer not found')
        return jsonify({'error': 'Customer not found'}), 404

    try:
        # Get data from the request
        data = request.form

        # Update customer details
        customer.name = data['name']
        customer.city = data['city']
        customer.age = data['age']

        # Commit the changes to the database
        db.session.commit()
        print('Customer updated succesfully')
        return redirect(url_for('customers.list_customers'))
    except Exception as e:
        # Handle any exceptions
        db.session.rollback()
        print('Error updating customer')
        return jsonify({'error': f'Error updating customer: {str(e)}'}), 500


# Route to delete a customer
@customers.route('/<int:customer_id>/delete', methods=['POST'])
def delete_customer(customer_id):
    customer = Customer.query.get(customer_id)
    if not customer:
        print('Customer not found')
        return jsonify({'error': 'Customer not found'}), 404

    try:
        # Delete the customer from the database
        db.session.delete(customer)
        db.session.commit()
        print('Customer deleted successfully')
        return redirect(url_for('customers.list_customers'))
    except Exception as e:
        # Handle any exceptions, such as database errors
        db.session.rollback()
        print('Error deleting customer')
        return jsonify({'error': f'Error deleting customer: {str(e)}'}), 500

Python/Flask_Book_Library/project/loans/__init__.py
# init file

Python/Flask_Book_Library/project/loans/views.py
from flask import render_template, Blueprint, request, redirect, url_for, jsonify
from project import db
from project.loans.models import Loan
from project.loans.forms import CreateLoan
from project.books.models import Book
from project.customers.models import Customer


# Blueprint for loans
loans = Blueprint('loans', __name__, template_folder='templates', url_prefix='/loans')


# Route to provide book and customer data in JSON format
@loans.route('/books/json', methods=['GET'])
def list_books_json():
    # Fetch all books from the database
    books = Book.query.all()
    # Create a list of book names
    book_list = [{'name': book.name} for book in books]
    # Return book data in JSON format
    return jsonify({'books': book_list})


# Route to list all customers
@loans.route('/customers/json', methods=['GET'])
def list_customers_json():

    # Fetch all customers from the database
    customers = Customer.query.all()
    # Create a list of customer names
    customer_list = [{'name': customer.name} for customer in customers]
    # Return customer data in JSON format
    return jsonify({'customers': customer_list})


# Route to list all loans
@loans.route('/', methods=['GET'])
def list_loans():
    # Fetch all loans from the database
    loans = Loan.query.all()
    # Render the loans.html template with the loans
    print('Loans page accessed')
    return render_template('loans.html', loans=loans, form=CreateLoan())


# Route to handle loan creation form
@loans.route('/create', methods=['POST'])
def create_loan():
    form = CreateLoan()

    if request.method == 'POST':
        
        # Process form submission
        customer_name = form.customer_name.data
        book_name = form.book_name.data
        loan_date = form.loan_date.data
        return_date = form.return_date.data

        # Check if the book is available
        book = Book.query.filter_by(name=book_name, status='available').first()
        if not book:
            print('Error. Book not available for loan.')
            return jsonify({'error': 'Book not available for loan.'}), 400

        try:
            # Create a new loan and store original book details
            new_loan = Loan(
                customer_name=customer_name,
                book_name=book_name,
                loan_date=loan_date,
                return_date=return_date,
                original_author=book.author,
                original_year_published=book.year_published,
                original_book_type=book.book_type
            )

            # Add the new loan to the database
            db.session.add(new_loan)
            db.session.commit()
            print('Loan added successfully')

            # Remove the book from the database
            db.session.delete(book)
            db.session.commit()

            # Redirect to the list of loans
            return redirect(url_for('loans.list_loans'))
        except Exception as e:
            db.session.rollback()
            error_message = f'Error creating loan: {str(e)}'
            # Log the error message
            print('Error creating loan:', error_message)
            return jsonify({'error': error_message}), 500

    # GET request, render the form
    print('GET request, render the form')
    return render_template('loans.html', form=form)


# Route to get loan data in JSON format
@loans.route('/json', methods=['GET'])
def list_loans_json():
    # Fetch all loans from the database
    loans = Loan.query.all()
    # Create a list of loan details
    loan_list = [{'customer_name': loan.customer_name, 'book_name': loan.book_name,
                  'loan_date': loan.loan_date, 'return_date': loan.return_date} for loan in loans]
    # Return loan data in JSON format
    return jsonify(loans=loan_list)


# Route to get customer data by name in JSON format
@loans.route('/customers/details/<string:customer_name>', methods=['GET'])
def get_customer_details(customer_name):
    # Find the customer by their name
    customer = Customer.query.filter_by(name=customer_name).first()

    if customer:
        # Create a dictionary with customer details
        customer_data = {
            'id': customer.id,
            'name': customer.name,
            'city': customer.city,
            'age': customer.age
        }
        # Return customer data in JSON format
        return jsonify(customer=customer_data)
    else:
        print('Customer not found')
        return jsonify({'error': 'Customer not found'}), 404


# Route to delete a loan
@loans.route('/<int:loan_id>/delete', methods=['POST'])
def delete_loan(loan_id):
    loan = Loan.query.get(loan_id)
    if not loan:
        print('Loan not found')
        return jsonify({'error': 'Loan not found'}), 404

    try:
        # Retrieve the book associated with the loan
        book = Book(
            name=loan.book_name,
            author=loan.original_author,
            year_published=loan.original_year_published,
            book_type=loan.original_book_type,
            status='available'  
        )

        # Add the book to the database
        db.session.add(book)

        # Delete the loan from the database
        db.session.delete(loan)
        db.session.commit()
        print('Loan deleted successfully')
        # Redirect to the list of loans
        return redirect(url_for('loans.list_loans'))
    except Exception as e:
        db.session.rollback()
        error_message = f'Error deleting loan: {str(e)}'
        print('Error deleting loan:', error_message)  # Log the error message
        return jsonify({'error': error_message}), 500


# Route to fetch loan details by ID
@loans.route('/<int:loan_id>/details', methods=['GET'])
def get_loan_details(loan_id):
    # Find the loan by ID
    loan = Loan.query.get(loan_id)

    if loan:
        # Create a dictionary with loan details
        loan_data = {
            'id': loan.id,
            'customer_name': loan.customer_name,
            'book_name': loan.book_name,
            'loan_date': loan.loan_date,
            'return_date': loan.return_date
        }
        # Return loan data in JSON format
        return jsonify(loan=loan_data)
    else:
        print('Loan not found')
        return jsonify({'error': 'Loan not found'}), 404


# Route to get book details by name in JSON format
@loans.route('/books/details/<string:book_name>', methods=['GET'])
def get_book_details(book_name):
    # Check if the book is in the "loans" database
    loaned_book = Loan.query.filter_by(book_name=book_name).first()

    if loaned_book:
        # Book is in "loans" database, return its details
        book_data = {
            'id': loaned_book.id,
            'name': loaned_book.book_name,
            'author': loaned_book.original_author,
            'year_published': loaned_book.original_year_published,
            'book_type': loaned_book.original_book_type
        }
        return jsonify(book=book_data)
    else:
        # Book not found in "loans" database, proceed to check "books" database
        book = Book.query.filter_by(name=book_name).first()

        if book:
            # Book found in "books" database, return its details
            book_data = {
                'id': book.id,
                'name': book.name,
                'author': book.author,
                'year_published': book.year_published,
                'book_type': book.book_type
            }
            return jsonify(book=book_data)
        else:
            # Book not found in both "loans" and "books" databases
            print('Book not found')
            return jsonify({'error': 'Book not found'}), 404

Python/Flask_Book_Library/project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <title>Book Library</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('core.index') }}">Book Library</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('books.list_books') }}">Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('customers.list_customers') }}">Customers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('loans.list_loans') }}">Loans</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JavaScript -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <!-- jQuery UI -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

</body>

</html>

Python/Flask_Book_Library/project/templates/books.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <h1 class="my-4">Books</h1>

    <!-- Link to trigger modal -->
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addBookModal">
        Add New Book
    </button>

    <!-- Search box -->
    <input type="text" id="searchInput" class="form-control mb-3" placeholder="Search for books..">

    <!-- Table to list books -->
    <table class="table table-bordered">
        <!-- Table header -->
        <thead>
            <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Year Published</th> <!-- New field: Year Published -->
                <th>Type</th> <!-- New field: Type -->
                <th>Actions</th>
            </tr>
        </thead>
        <!-- Table body -->
        <tbody>
            <!-- Loop through books and display each book -->
            {% for book in books %}
            <tr>
                <td>{{ book.name | safe }}</td>
                <td>{{ book.author | safe }}</td>
                <td>{{ book.year_published }}</td> <!-- Display Year Published -->
                <td>{{ book.book_type }}</td> <!-- Display Book Type -->
                <td>
                    <!-- Inside the <td> for "Edit" button -->
                    <button class="btn btn-warning btn-sm" onclick="editBook({{ book.id }})">Edit</button>

                    <!-- Inside the <td> for "Delete" button -->
                    <button class="btn btn-danger btn-sm" onclick="deleteBook({{ book.id }})">Delete</button>


                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<!-- Add Book Modal -->
<div class="modal fade" id="addBookModal" tabindex="-1" role="dialog" aria-labelledby="addBookModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addBookModalLabel">Add New Book</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Add Book Form -->
                <form id="addBookForm">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" placeholder="Enter book name" required>
                    </div>
                    <div class="form-group">
                        <label for="author">Author</label>
                        <input type="text" class="form-control" id="author" placeholder="Enter author name" required>
                    </div>
                    <div class="form-group">
                        <label for="year_published">Year Published</label>
                        <input type="number" class="form-control" id="year_published" placeholder="Enter year published"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="book_type">Type</label>
                        <select class="form-control" id="book_type" required>
                            <option value="2days">2 Days</option>
                            <option value="5days">5 Days</option>
                            <option value="10days">10 Days</option>
                        </select>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Add Book</button>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Edit Book Modal -->
<div class="modal fade" id="editBookModal" tabindex="-1" role="dialog" aria-labelledby="editBookModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editBookModalLabel">Edit Book</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Edit Book Form -->
                <form id="editBookForm">
                    <div class="form-group">
                        <label for="edit_name">Name</label>
                        <input type="text" class="form-control" id="edit_name" placeholder="Enter book name" required>
                    </div>
                    <div class="form-group">
                        <label for="edit_author">Author</label>
                        <input type="text" class="form-control" id="edit_author" placeholder="Enter author name"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="edit_year_published">Year Published</label>
                        <input type="number" class="form-control" id="edit_year_published"
                            placeholder="Enter year published" required>
                    </div>
                    <div class="form-group">
                        <label for="edit_book_type">Type</label>
                        <select class="form-control" id="edit_book_type" required>
                            <option value="2days">2 Days</option>
                            <option value="5days">5 Days</option>
                            <option value="10days">10 Days</option>
                        </select>
                    </div>

                    <button type="button" class="btn btn-primary" id="saveEditBookButton">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Include Axios -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<!-- Custom JavaScript file (books.js) -->
<script src="{{ url_for('static', filename='js/books.js') }}"></script>


{% endblock %}

Python/Flask_Book_Library/project/templates/index.html
{% extends 'base.html' %}

{% block content %}
<br>
    <h1>Welcome to the Book library</h1>

{% endblock %}

Python/Flask_Book_Library/project/templates/loans.html
{% extends 'base.html' %}
{% block content %}


<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

<div class="container">
    <h1 class="my-4">Loans</h1>

    <!-- Link to trigger modal -->
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addLoanModal">
        Add New Loan
    </button>

    <!-- Search box -->
    <input type="text" id="searchInput" class="form-control mb-3" placeholder="Search for loans..">

    <!-- Table to list loans -->
    <table class="table table-bordered">
        <!-- Table header -->
        <thead>
            <tr>
                <th>Customer Name</th>
                <th>Book Name</th>
                <th>Loan Date</th>
                <th>Return Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <!-- Table body -->
        <tbody>
            <!-- Loop through loans and display each loan -->
            {% for loan in loans %}
                <tr>
                    <td>{{ loan.customer_name | safe }}</td>
                    <td>{{ loan.book_name | safe }}</td>
                    <td>{{ loan.loan_date }}</td>
                    <td>{{ loan.return_date }}</td>
                    <td>
                        <button class="btn btn-danger btn-sm delete-button" data-loan-id="{{ loan.id }}">End Loan</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<!-- Add loan Modal -->
<div class="modal fade" id="addLoanModal" tabindex="-1" role="dialog" aria-labelledby="addLoanModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addLoanModalLabel">Add New Loan</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="addLoanForm" action="/loans/create" method="POST">
                    {{ form.hidden_tag() }}
            
                    <div class="form-group">
                        <label for="customer_name">Customer Name</label>
                        <select class="form-control" id="customer_name" name="customer_name">
                            <!-- Options will be populated dynamically by JavaScript -->
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="book_name">Book Name</label>
                        <select class="form-control" id="book_name" name="book_name">
                            <!-- Options will be populated dynamically by JavaScript -->
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="loan_date">Loan Date</label>
                        <!-- Use type="date" for a date picker -->
                        <input type="date" class="form-control" id="loan_date" name="loan_date" required>
                    </div>
                    <div class="form-group">
                        <label for="return_date">Return Date</label>
                        <!-- Use type="date" for a date picker -->
                        <input type="date" class="form-control" id="return_date" name="return_date" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Loan</button>
                </form>
            </div>
            

        </div>
    </div>
</div>


<!-- Include Axios -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<!-- Custom JavaScript file (loans.js) -->
<script src="{{ url_for('static', filename='js/loans.js') }}"></script>

{% endblock %}